import { TableColumn } from '../../../shared/components/tables/tables';
import { FilterOption } from '../../../shared/components/filter/filter';
import { Raffle } from '../../interfaces/raffle.interface';

export const DEFAULT_RAFFLE_START_DATE = '2026-05-10';
export const DEFAULT_RAFFLE_END_DATE = '2026-05-20';
export const DEFAULT_RAFFLE_META = 10000;
export const DEFAULT_RAFFLE_TICKETS_TOTAL = 100;
export const DEFAULT_RAFFLE_TICKET_PRICE = 5;
export const DEFAULT_RAFFLE_BENEFICIARY_PERCENT = 80;
export const DEFAULT_RAFFLE_WINNER_PERCENT = 20;
export const DEFAULT_RAFFLE_BLOG_CARD = 'Ayuda a personas necesitadas.';
export const DEFAULT_RAFFLE_BLOG_DETAIL = 'Esta rifa apoya la causa social.';
export const DEFAULT_RAFFLE_TIME_LEFT = '15 dias';


export const MY_RAFFLES_PRINCIPAL_HEADER = 'Rifas Activas';

export const MY_RAFFLES_COLUMNS: TableColumn[] = [
  { field: 'nombreRifa', header: 'Nombre Rifa' },
  { field: 'fundacion', header: 'Fundación' },
  { field: 'categoria', header: 'Categoría' },
  { field: 'estado', header: 'Estado', type: 'badge' },
  { field: 'boletosVendidosStr', header: 'Boletos Vendidos' },
  { field: 'recaudadoStr', header: 'Total Recaudado' },
  { field: 'tiempoRestante', header: 'Tiempo Restante' },
  { field: 'acciones', header: 'Acciones', type: 'actions' },
];

export const RAFFLE_FILTER_ALL = 'all';
export const RAFFLE_FILTER_NO_TICKETS = 'sin-boletos';
export const RAFFLE_FILTER_PROX_EXPIRED = 'proximo-vencer';
export const RAFFLE_FILTER_META_COMPLETED = 'meta-completada';

export const RAFFLE_STATUS_ACTIVE = 'Activo';
export const RAFFLE_STATUS_INACTIVE = 'Inactivo';
export const RAFFLE_STATUS_NO_TICKETS = 'SIN BOLETOS';
export const RAFFLE_STATUS_PROX_EXPIRED = 'PROXIMO A VENCER';
export const RAFFLE_STATUS_META_COMPLETED = 'META COMPLETADA';

export const MY_RAFFLES_FILTERS: FilterOption[] = [
  { id: RAFFLE_FILTER_ALL, icon: 'bi-list-ul', label: 'Todo' },
  { id: RAFFLE_FILTER_NO_TICKETS, icon: 'bi-ticket-perforated', label: 'Sin Boletos' },
  { id: RAFFLE_FILTER_PROX_EXPIRED, icon: 'bi-hourglass', label: 'Próximo a vencer' },
  { id: RAFFLE_FILTER_META_COMPLETED, icon: 'bi-check-all', label: 'Meta Completada' },
];

export const MY_RAFFLES_DATA_MOCK: Raffle[] = [
  {
    id: 1,
    nombreRifa: 'Calidad de vida a personas de la tercera edad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'SIN BOLETOS',
    boletosVendidos: 100,
    boletosTotales: 100,
    recaudado: 10000,
    meta: 10000,
    ganador: '',
    tiempoRestante: '10 dias',
    acciones: '',
    startDate: '2026-05-01',
    endDate: '2026-05-15',
    ticketPrice: 100,
    beneficiaryPercentage: 80,
    winnerPercentage: 20,
    blogCardText: 'Ayuda a personas de la tercera edad',
    blogDetailText: 'Esta rifa apoya a Caritas Tijuana A.C. en sus comedores sociales.',
    photo:
      'https://images.unsplash.com/photo-1516841273335-e39b37888115?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 2,
    nombreRifa: 'Rifa de Reyes',
    fundacion: 'Fundación Teletón',
    categoria: 'TECNOLOGIA',
    estado: 'PROXIMO A VENCER',
    boletosVendidos: 95,
    boletosTotales: 100,
    recaudado: 9500,
    meta: 10000,
    ganador: '',
    tiempoRestante: '2 dias',
    acciones: '',
    startDate: '2026-05-05',
    endDate: '2026-05-20',
    ticketPrice: 100,
    beneficiaryPercentage: 75,
    winnerPercentage: 25,
    blogCardText: 'Equipamiento médico infantil',
    blogDetailText: 'Esta rifa apoya la compra de incubadoras para el Hospital Infantil.',
    photo:
      'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 3,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'META COMPLETADA',
    boletosVendidos: 100,
    boletosTotales: 100,
    recaudado: 10000,
    meta: 10000,
    ganador: '',
    tiempoRestante: '10 dias',
    acciones: '',
    startDate: '2026-05-10',
    endDate: '2026-05-25',
    ticketPrice: 100,
    beneficiaryPercentage: 80,
    winnerPercentage: 20,
    blogCardText: 'Apoyo invernal para el asilo',
    blogDetailText: 'Esta rifa apoya con insumos médicos y calefactores para el Asilo San Pedro.',
    photo:
      'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 4,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 5,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 6,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 7,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 8,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 9,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 10,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 11,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 12,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 13,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 14,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 15,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 16,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 17,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 18,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 19,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 20,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Banco de Alimentos',
    categoria: 'ASISTENCIA SOCIAL',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
];
