import { TableColumn } from '../../../shared/components/tables/tables';
import { FilterOption } from '../../../shared/components/filter/filter';
import { Raffle } from '../../../features/rifas/pages/my-raffles/my-raffles';

export const MY_RAFFLES_PRINCIPAL_HEADER = 'Rifas Activas';

export const MY_RAFFLES_COLUMNS: TableColumn[] = [
  { field: 'nombreRifa', header: 'Nombre Rifa' },
  { field: 'fundacion', header: 'Fundación' },
  { field: 'categoria', header: 'Categoría' },
  { field: 'estado', header: 'Estado', type: 'badge' },
  { field: 'boletosVendidosStr', header: 'Boletos Vendidos' },
  { field: 'recaudadoStr', header: 'Total Recaudado' },
  { field: 'tiempoRestante', header: 'Tiempo Restante' },
  { field: 'acciones', header: 'Acciones', type: 'actions' },
];

export const RAFFLE_FILTER_ALL = 'all';
export const RAFFLE_FILTER_NO_TICKETS = 'sin-boletos';
export const RAFFLE_FILTER_PROX_EXPIRED = 'proximo-vencer';
export const RAFFLE_FILTER_META_COMPLETED = 'meta-completada';

export const RAFFLE_STATUS_ACTIVE = 'Activo';
export const RAFFLE_STATUS_INACTIVE = 'Inactivo';
export const RAFFLE_STATUS_NO_TICKETS = 'SIN BOLETOS';
export const RAFFLE_STATUS_PROX_EXPIRED = 'PROXIMO A VENCER';
export const RAFFLE_STATUS_META_COMPLETED = 'META COMPLETADA';

export const MY_RAFFLES_FILTERS: FilterOption[] = [
  { id: RAFFLE_FILTER_ALL, icon: 'bi-list-ul', label: 'Todo' },
  { id: RAFFLE_FILTER_NO_TICKETS, icon: 'bi-ticket-perforated', label: 'Sin Boletos' },
  { id: RAFFLE_FILTER_PROX_EXPIRED, icon: 'bi-hourglass', label: 'Próximo a vencer' },
  { id: RAFFLE_FILTER_META_COMPLETED, icon: 'bi-check-all', label: 'Meta Completada' },
];

export const MY_RAFFLES_DATA_MOCK: Raffle[] = [
  {
    id: 1,
    nombreRifa: 'Calidad de vida a personas de la tercera edad',
    fundacion: 'Cáritas Tijuana A.C.',
    categoria: 'AYUDA SOCIAL',
    estado: 'SIN BOLETOS',
    boletosVendidos: 100,
    boletosTotales: 100,
    recaudado: 10000,
    meta: 10000,
    ganador: '',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 2,
    nombreRifa: 'Rifa de Reyes',
    fundacion: 'Hospital Infantil',
    categoria: 'Electronicos',
    estado: 'PROXIMO A VENCER',
    boletosVendidos: 95,
    boletosTotales: 100,
    recaudado: 9500,
    meta: 10000,
    ganador: '',
    tiempoRestante: '2 dias',
    acciones: '',
  },
  {
    id: 3,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'META COMPLETADA',
    boletosVendidos: 100,
    boletosTotales: 100,
    recaudado: 10000,
    meta: 10000,
    ganador: '',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 4,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 5,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 6,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 7,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 8,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 9,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 10,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 11,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 12,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 13,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 14,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 15,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 16,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 17,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 18,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 19,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
  {
    id: 20,
    nombreRifa: 'Rifa de Navidad',
    fundacion: 'Asilo San Pedro',
    categoria: 'Autos',
    estado: 'Activo',
    boletosVendidos: 50,
    boletosTotales: 100,
    recaudado: 5000,
    meta: 10000,
    ganador: 'Juan Perez',
    tiempoRestante: '10 dias',
    acciones: '',
  },
];
